## IMPORT LIBRARIES

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
%matplotlib

Using matplotlib backend: module://matplotlib_inline.backend_inline

## IMPORT DATASET

In [2]:
data = pd.read_csv("customer_shopping_behavior.csv")

## BASIC CHECKS

In [3]:
data.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [4]:
data.tail()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [6]:
data.describe().T

,count,mean,std,min,25%,50%,75%,max
Customer ID,3900.0,1950.500000,1125.977353,1.0,975.75,1950.5,2925.25,3900.0
Age,3900.0,44.068462,15.207589,18.0,31.00,44.0,57.00,70.0
Purchase Amount (USD),3900.0,59.764359,23.685392,20.0,39.00,60.0,81.00,100.0
Review Rating,3863.0,3.750065,0.716983,2.5,3.10,3.8,4.40,5.0
Previous Purchases,3900.0,25.351538,14.447125,1.0,13.00,25.0,38.00,50.0

In [7]:
data.describe(include = "all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Customer ID,3900.0,NaN,NaN,NaN,1950.5,1125.977353,1.0,975.75,1950.5,2925.25,3900.0
Age,3900.0,NaN,NaN,NaN,44.068462,15.207589,18.0,31.0,44.0,57.0,70.0
Gender,3900,2,Male,2652,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Item Purchased,3900,25,Blouse,171,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Category,3900,4,Clothing,1737,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Purchase Amount (USD),3900.0,NaN,NaN,NaN,59.764359,23.685392,20.0,39.0,60.0,81.0,100.0
Location,3900,50,Montana,96,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Size,3900,4,M,1755,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Color,3900,25,Olive,177,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Season,3900,4,Spring,999,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Review Rating,3863.0,NaN,NaN,NaN,3.750065,0.716983,2.5,3.1,3.8,4.4,5.0
Subscription Status,3900,2,No,2847,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Shipping Type,3900,6,Free Shipping,675,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Discount Applied,3900,2,No,2223,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Promo Code Used,3900,2,No,2223,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Previous Purchases,3900.0,NaN,NaN,NaN,25.351538,14.447125,1.0,13.0,25.0,38.0,50.0
Payment Method,3900,6,PayPal,677,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Frequency of Purchases,3900,7,Every 3 Months,584,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
data.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [9]:
data.duplicated().sum()

np.int64(0)

## HANDLE NULL VALUES

In [10]:
data["Review Rating"] = data.groupby("Category")["Review Rating"].transform(lambda x : x.fillna(x.median()))

## FEATURE ENGINEERING

In [11]:
# Change the column name into lowercase 
data.columns = data.columns.str.lower()
data.columns = data.columns.str.replace(" ","_")
data = data.rename(columns = {"purchase_amount_(usd)": "purchase_amount"})

In [12]:
data.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [13]:
# Create a new column with existing column
labels = ["Young Adult", "Adult", "Middle age", "Senior"]
data["age_group"] = pd.qcut(data["age"], q = 4, labels = labels)

In [14]:
data.frequency_of_purchases.value_counts()

frequency_of_purchases
Every 3 Months    584
Annually          572
Quarterly         563
Monthly           553
Bi-Weekly         547
Fortnightly       542
Weekly            539
Name: count, dtype: int64

In [15]:
# Create a column frequently purchased days
purchase = {
    "Weekly" : 7,
    "Fortnightly" : 14,
    "Bi-Weekly" : 14,
    "Monthly" : 30,
    "Quarterly" : 90,
    "Annually" : 365,
    "Every 3 Months" : 90
}
data["purchase_frequency_days"] = data["frequency_of_purchases"].map(purchase)

In [16]:
# Check both value represent same result
(data["discount_applied"] == data["promo_code_used"]).all()

np.True_

In [17]:
data = data.drop("promo_code_used", axis = 1)

## CODE TO CONNECT THE MYSQL

In [18]:
pip install mysql-connector-python sqlalchemy

Requirement already satisfied: mysql-connector-python in c:\users\abish\appdata\local\programs\python\python313\lib\site-packages (9.7.0)
Requirement already satisfied: sqlalchemy in c:\users\abish\appdata\local\programs\python\python313\lib\site-packages (2.0.49)
Requirement already satisfied: greenlet>=1 in c:\users\abish\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (3.5.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\abish\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [19]:
# Connect it into the mysql
username = "root"
password = "root"
host = "localhost"
port = "3306"
database = "customer_behaviour"

In [20]:
from sqlalchemy import create_engine

engine = create_engine("mysql+mysqlconnector://root:root@localhost:3306/customer_behaviour")

In [21]:
table_name = "customer"

data.to_sql(table_name, engine, if_exists="replace", index=False)

print("Data loaded successfully")

Data loaded successfully